# -*- coding: utf-8 -*-
"""SummarizeLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqCnh_oA_bfxZpCJpJAIdcRhWvOILI8J
"""

!pip install transformers torch

from transformers import pipeline

bart_summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

text = """
The red-billed quelea (Quelea quelea) is a small, migratory, sparrow-like bird of the weaver family, Ploceidae, native to sub-Saharan Africa. It is approximately 12 cm (4.7 in) long and weighs 15 to 26 g (0.53 to 0.92 oz) Non-breeding birds have light underparts, striped brown upper parts, yellow-edged flight feathers and a reddish bill. Breeding females attain a yellowish bill. Breeding males have a black (or rarely white) facial mask, surrounded by a purplish, pinkish, rusty or yellowish wash on the head and breast. The species avoids forests, deserts and colder areas. It constructs oval roofed nests woven from strips of grass hanging from thorny branches, sugar cane or reeds. It breeds in very large colonies. The quelea feeds primarily on seeds of annual grasses, but also causes extensive damage to cereal crops. It is regarded as the most numerous undomesticated bird on earth, with the population sometimes peaking at an estimated 1.5 billion individuals.
"""

summary = bart_summarizer(text, max_length=150, min_length=50, do_sample=False)
print("BART Summary:\n", summary[0]['summary_text'])

from transformers import set_seed

gpt2_refiner = pipeline("text-generation", model="gpt2")
set_seed(42)

prompt = (
    "Summarize this paragraph in ONE short sentence only. "
    "Do not explain or add examples.\n\n"
    f"{summary[0]['summary_text']}"
)
output = gpt2_refiner(
    prompt,
    max_new_tokens=20,     # use max_new_tokens instead of max_length
    temperature=0.4,
    num_return_sequences=1
)

print("Refined Summary:\n", output[0]['generated_text'])

from transformers import pipeline, set_seed

set_seed(42)
refiner = pipeline("text-generation", model="gpt2")

text = """The red-billed quelea is a small, migratory, sparrow-like bird of the weaver family..."""

# Keep only essential part if text is long
text = text[:700]   # trim long input so GPT-2 keeps the prompt visible

prompt = (
    "Summarize this paragraph in ONE short sentence only. "
    "Do not explain or add examples.\n\n"
    f"{text}\n\nSummary:"
)

output = refiner(
    prompt,
    max_new_tokens=50,     # use max_new_tokens instead of max_length
    temperature=0.4,
    num_return_sequences=1
)

result = output[0]['generated_text'].split("Summary:")[-1].split('.')[0].strip() + '.'
print("Refined Summary:", result)